"""add mission creator

Revision ID: 041f8c612868
Revises: 347ab2824fa6
Create Date: 2026-08-15 15:21:09.887392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041f8c612868'
down_revision: Union[str, Sequence[str], None] = '347ab2824fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'missions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_column('missions', 'created_by')
    # ### end Alembic commands ###
